[package]
name = "rust_velocimeter_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cargo for blockchain interactions
ethers = { version = "2.0", features = ["rustls"] }
# Ethers' async features rely upon the Tokio async runtime.
futures = "0.3.28"
# Flexible concrete Error Reporting type built on std::error::Error with customizable Reports
eyre = "0.6"
# env variable from .env
dotenv = "0.15.0"

# For caching and serving data
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
axum = "0.6.20"
axum-macros = "0.3.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Ethers and axum relays on tokio
tokio = { version = "1.0", features = ["full"] }

# For HTTP requests
reqwest = "0.11.20"

[build-dependencies]
ethers = { version = "2.0", features = ["abigen"] }
