//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "o_token_datas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: i32,
    #[sea_orm(column_type = "Double")]
    pub average_lock_time: f64,
    #[sea_orm(column_type = "Double")]
    pub w_native_rewarded: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
